name: Build and Upload Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  data-versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get SDK version
        id: get_version
        run: |
          VERSION=$(jq -r '.docker_image' config.json | cut -d ':' -f 2)
          echo "SDK_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: supervisely/data-versioning
          tags: ${{ env.SDK_VERSION }}, latest
          addLatest: true
          dockerfile: "Dockerfile"
          registry: docker.io
          buildArgs: |
            version=${{ env.SDK_VERSION }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
