name: Build test image and Release App Branch
run-name: Build test image and Release "${{ github.ref_name }}" branch
on:
  push:
    branches-ignore:
      - main
      - master

env:
  BUILD_TEST_IMAGE_ON_RELEASE: "true"

jobs:
  Supervisely-Release-Branch:
    uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
    with:
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: "${{ github.ref_name }}"
      RELEASE_DESCRIPTION: "'${{ github.ref_name }}' branch release"
      RELEASE_TYPE: "release-branch"
      SUBAPP_PATHS: "__ROOT_APP__"
